#+TITLE: Аннотированный отчет за 2017
#+AUTHOR: Черкашин Евгений Александрович
#+LATEX_HEADER: \usepackage{unicode-math}
#+LATEX_HEADER: \setmainfont{XITS}
#+LATEX_HEADER: \setmathfont{XITS Math}
#+LATEX_HEADER: \setmathfont[range={\mathcal,\mathbfcal},StylisticSet=1]{XITS Math}

* A formula for lua
\begin{equation}
  \left( \frac{P^2}{2m} + V(x,y,z) \right) Ψ = E Ψ
\end{equation}

* Задачи, которые требовалось решить в 2017 году
** Отработка методов выделения суммарной ДНК из разных источников (вода, донные отложения) для секвенирования библиотек ампликонов фрагментов маркерных генов 16S (прокариоты) и 18S (эукариоты) рРНК и фрагментных метагеномных библиотек с целью получения информации о таксономической структуре эукариотических организмов в сообществах, соответствующей данным микроскопических методов анализа.
** Отбор проб из фотического слоя и донных осадков (до 100), выделение ДНК, секвенирование библиотек ампликонов 16S и 18S рРНК (общий объем секвенирования – 1-2 запуска Illumina MiSeq или аналогичный), таксономический анализ сообществ.
** Подготовка материалов для регистрации выделенных в культуру бактерий во Всероссийскую коллекцию микроорганизмов (ВКМ) (г. Пущино) и немецкую коллекцию микроорганизмов и клеточных культур, г. Лейбниц, Германия (DSMZ).
** Отработка алгоритмов биоинформатического анализа результатов секвенирования фрагментных метагеномных библиотек.
** Разработка онтологии и технологии унифицированного доступа к данным результатов исследований на основе Linked-Data и современных стандартов представления данных о биомах. Интеграция хранилища данных проекта в мировую информационную среду.

Исследования велись по следующим направлениям:

1. Поиск онтологий для представления публикуемых документов.
2. Разработка системы хранения и обеспечения публикуемых документов в частично формализованном виде.
3. Создание средств обеспечения доступа к документам, включая поиск по содержимому.
4. Разработка программной системы для построения логического вывода на данных документов.
5. Создание инфраструктуры для проведения анализа текстов хранимых документов с целью выявления новых данных разметки.

** Анализ современного программного обеспечения обработки BD, используемого в приложениях NGS, в том числе, удалении адаптеров и химер, проверке качества данных, таксономической идентификации, картировании прочтений, сборки de novo, анализе ампликонов, реконструкции метаболических путей и аннотации последовательностей. Выбор оптимального ПО для обработки данных
** Подготовка технических предложений по проектированию и реализации ИОБД, предназначенной для архивирования, управления, курирования, анализа и визуализации данных, получаемых в результате исследования микробиома биоинформационными технологиями и NGS.
** Проектирование схемы Хранилища Больших Данных (ХБД) для обеспечения управления данными, используемыми при исследовании микробиома Байкала, а также веб-публикации для поиска нуклеотидных и аминокислотных последовательностей по заданным таксонам и параметрам среды обитания.
** Для построения полисистемы динамических моделей выделение сквозных концептов, имеющих качественный характер, и базовых взаимосвязей между ними. Проведение серии пробных идентификаций параметров.

Проведены следующие исследования:

1. Произведен обзор литературы по тематике моделирования микробиомов в естественной среде.
2. Разработан метод идентификации динамической модели микробиома оз.Байкал на основе данных мониторинга.
3. Предложена методика вычисления начальных условий модели.

Разработан ряд технологий продержки процесса моделирования:

1. Программная подсистема визуализации и редактирования структуры модели, представляющая модели в виде ориентированного графа взаимодействия компонентов.
2. Подсистема расчетов, визуализации и сравнения сценариев использования модели.
